rvm:
  - 2.4.4
  - 2.6.3
  - ruby-head
gemfile:
  - gemfiles/Gemfile.hanami-1.3.x
  - Gemfile
notifications:
  recipients:
    - marcelo.jacobus@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head

